# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-02 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191003_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
